<?php


/**
 * Implements hook_user_login().
 */

function custom_user_login(\Drupal\user\UserInterface $account) {
    
    $session = \Drupal::request()->getSession();
    $id = $session->get('current_id');
    if(!empty($id)){
        $current_request = \Drupal::service('request_stack')->getCurrentRequest();
        if (!$current_request->query->get('destination')) {
            $current_request->query->set(
                'destination',
                \Drupal\Core\Url::fromRoute('entity.node.canonical', ['node' => $id])->toString()
            );
        }
    }
}