auth:
  social_auth_google:
    route: social_auth_google.redirect_to_google
    img_path: modules/social_auth_google/img/google_logo.svg
post_login: '<front>'
redirect_user_form: false
disable_admin_login: false
disabled_roles:
  administrator: '0'
user_allowed: register
_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
